### ISSUE TITLE
Disowning package fails when package has had an orphan request that got rejected previoulsy

### ISSUE THREAD

**Issue by zocker-160** [makedeb/mprweb#9] opened 2021-12-21 13:09 UTC
Image of the error:
![image](https://user-images.githubusercontent.com/36563538/146935197-45ea4af9-1237-494f-8825-46806bad2234.png)

## How to reproduce

- select some package
- issue an orphan request
- go into requests as TU
- close / reject orphan request
- go back to the package and press `disown package`
- press `disown`
- get error as shown above

Expected behaviour would be that disowning a package should always work regarding of any pending or rejected orphan requests.

**Comment by hwittenborn** [comment] 2022-03-06 20:24
Does this still happen @zocker-160?

**Comment by zocker-160** [comment] 2022-03-06 21:45
@hwittenborn I sadly do not have a package to test that on

**Comment by hwittenborn** [comment] 2022-03-06 21:49
I'll just close the issue for now then - feel free to send a message here if any issue happens again.

**Closed as completed by hwittenborn** 2022-03-06 21:49 UTC

**Comment by zocker-160** [comment] 2022-03-06 21:52
uhm did you even try to reproduce?

**Comment by hwittenborn** [comment] 2022-03-06 22:04
I'm not sure what to test it on either @zocker-160, but we can reopen the issue if it pops up again.

It's not that I'm doubting the issue is happening, it's just that if we can't verify it then I'd rather it be closed until we can, as it's cluttering up the open issues otherwise.
